services:
  unbgeology.mongodb.lib.unb.ca:
    build:
      context: .
    env_file:
      - ./env/mongodb.env
    restart: unless-stopped
    container_name: unbgeology.mongodb.lib.unb.ca
    expose:
      - "27017"
    volumes:
      - mongodb-data:/var/lib/mongodb
volumes:
  mongodb-data:
